import type { Metadata } from 'next';
import { Toaster } from '@/components/ui/toaster';
import AppProvider from '@/context';

import Header from './_components/header/header';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AppProvider>
      <html lang="ja">
        <body
          className="min-h-full bg-backGround-primary"
        >
          <Header title="アンケート" variant="simple" icon={<img alt="" width={30} height={30} src="/image/arrow_forward_ios.svg"></img>} />
          {children}
          <Toaster />
        </body>
      </html>
    </AppProvider>

  );
}
